name: "Securing Workflows"
description: "Runs StepSecurity and Canary Tokens"
author: "Your Name"

inputs:
  aws_credentials:
    description: "AWS credentials secret"
    required: true

  run_canary:
    description: "Enable CanaryTokens step"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
  
  # Write if condition here to use Custom properties or topics
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 #testing a broken step action
      with:
        egress-policy: audit
        allowed-endpoints: >
          api.github.com:443
          github.com:443
      continue-on-error: true
     
    - name: Show the current branch
      shell: bash
      run: |
        echo "Current ref is: $GITHUB_REF"
        echo "Repository is: $GITHUB_REPOSITORY"

    - name: Capture workflow run ID
      id: capture_run_id
      shell: bash
      run: |
        echo "run_id=$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

    - name: Run Canary Token Deployment
      if: ${{ inputs.run_canary == 'true' }}
      uses: ./.github/actions/csirt-test

