name: "Securing Workflows"
description: "Runs StepSecurity and Canary Tokens"
author: "Your Name"

runs:
  using: "composite"
  steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2
      with:
        egress-policy: audit
        
    - name: Show the current branch
      shell: bash
      run: |
        echo "Current ref is: $GITHUB_REF"
        echo "Repository is: $GITHUB_REPOSITORY"
        # echo "Message: ${{ inputs.message }}"
        # RUN_ID of workflow
        # RUN workflow ID

    - name: Configure AWS Credentials
      shell: bash
      run: |
        mkdir -p ~/.aws
        echo "${{ secrets.AWS }}" > ~/.aws/credentials.backup.donotuse
        chmod 600 ~/.aws/credentials.backup.donotuse
