name: "Securing Workflows"
description: "Runs StepSecurity and Canary Tokens"
author: "Your Name"

inputs:
  aws_credentials:
    description: "AWS credentials secret"
    required: true

runs:
  using: "composite"
  steps:
  # Write if condition here to use Custom properties or topics
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 #testing a broken step action
      with:
        egress-policy: audit
        allowed-endpoints: >
          api.github.com:443
          github.com:443
      continue-on-error: true
     
    - name: Show the current branch
      shell: bash
      run: |
        echo "Current ref is: $GITHUB_REF"
        echo "Repository is: $GITHUB_REPOSITORY"

    - name: Capture workflow run ID
      id: capture_run_id
      shell: bash
      run: |
        echo "run_id=$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      shell: bash
      run: |
        mkdir -p ~/.aws
        echo "${{ inputs.aws_credentials }}" > ~/.aws/credentials.backup.donotuse
        chmod 600 ~/.aws/credentials.backup.donotuse
