name: "Securing Workflows"
description: "Runs Canary Tokens"
author: "Your Name"

inputs:
  aws_credentials:
    description: "AWS credentials secret"
    required: true

runs:
  using: "composite"
  steps:
  # Write if condition here to use Custom properties or topics

    - name: Configure AWS Credentials
      shell: bash
      run: |
        mkdir -p ~/.aws
        echo "${{ inputs.aws_credentials }}" > ~/.aws/credentials.backup.donotuse
        chmod 600 ~/.aws/credentials.backup.donotuse
